version: "3.9"

services:
  backend:
    build: ./backend
    container_name: express_ir
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app
      - /app/node_modules
    environment:
      DATABASE_URL: ${DATABASE_URL}
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}

  batch:
    build: ./batch
    container_name: batch_ir
    depends_on:
      - backend
    environment:
      BACKEND_URL: ${BACKEND_URL}
      CRON_SCHEDULE: ${CRON_SCHEDULE}

  frontend:
    build: ./frontend
    container_name: vue_ir
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    stdin_open: true
    tty: true
